apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chaptergen-main-ingress
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - chapgen.app
    secretName: chapgen-app-tls
  rules:
  - host: chapgen.app
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80
      - path: /process-youtube-url
        pathType: Prefix
        backend:
          service:
            name: youtube-ingestion-service
            port:
              number: 8000
      - path: /ws/
        pathType: Prefix
        backend:
          service:
            name: frontend-bridge-service
            port:
              number: 8765
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chaptergen-db-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - chapgen.app
    secretName: chapgen-app-tls
  rules:
  - host: chapgen.app
    http:
      paths:
      - path: /api/db(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: database-service-service
            port:
              number: 8008
