apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: yourEmail@example.com # Change the email here to a valid email address.
    privateKeySecretRef:
      name: letsencrypt-prod-private-key
    solvers:
    - http01:
        ingress:
          ingressTemplate:
            metadata:
              annotations:
                nginx.ingress.kubernetes.io/acme-challenge-path-type: "Prefix"
          class: nginx
