name: Continuous Deployment

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          script: |
            echo "--- Deploying new images to Kubernetes ---"
            sudo kubectl rollout restart deployment youtube-ingestion-deployment
            sudo kubectl rollout restart deployment transcription-bridge-deployment
            sudo kubectl rollout restart deployment chapter-generation-deployment
            sudo kubectl rollout restart deployment database-service-deployment
            sudo kubectl rollout restart deployment frontend-bridge-deployment
            echo "--- Rollout complete ---"
